---
driver:
  name: docker
  socket: unix:///var/run/docker.sock
  privileged: true
  use_sudo: false
  hostname: "simple"

provisioner:
  name: ansible_push
  chef_bootstrap_url: nil
  ansible_config: "test/ansible.cfg"
  idempotency_test: true
  diff: true

platforms:
  - name: fedora-25
    driver:
      run_command: /start
      run_options: --tty -e 'container=docker'
      provision_command:
        - dnf install -y python systemd
      volume:
        - $PWD/test/init_scripts/fedora:/start:ro
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

verifier:
  name: inspec

suites:
  - name: default
    provisioner:
      playbook: "test/integration/default/ansible/playbook.yml"

  - name: configured
    provisioner:
      playbook: "test/integration/configured/ansible/playbook.yml"
