---
- name: Clean configuration directory
  file:
    path: "{{ logstash_cfg_dir }}"
    state: absent
  when: logstash_clean_cfg_dir

- name: Ensure configuration directory exists
  file:
    path: "{{ logstash_cfg_dir }}"
    state: directory
    owner: logstash
    group: logstash

- name: Add static configuration files
  copy:
      src: "{{ item }}"
      dest: "{{ logstash_cfg_dir }}"
  with_items: "{{ logstash_cfg_files }}"
  register: static_cfg

- name: Add configuration from templates
  template:
      src: "{{ item }}"
      dest: "{{ logstash_cfg_dir }}"
  with_items: "{{ logstash_cfg_templates }}"
  register: template_cfg

- name: Add static configuration files using regex
  copy:
      src: "{{ item }}"
      dest: "{{ logstash_cfg_dir }}"
  with_fileglob: "{{ logstash_cfg_files_regex }}"
  register: static_regex_cfg

- name: Add configuration from templates using regex
  template:
      src: "{{ item }}"
      dest: "{{ logstash_cfg_dir }}"
  with_fileglob: "{{ logstash_cfg_templates_regex }}"
  register: template_regex_cfg

- name: Restart Logstash service
  command: systemctl restart logstash
  when:
    - static_cfg.changed
    - template_cfg.changed
    - static_regex_cfg.changed
    - template_regex_cfg.changed

